database:
  host: localhost
  port: 5432
  user: swagstaf
  password: qwerty_pwd
  name: db_mp
  sslmode: disable
  migrations: internal/migrations

nats:
  cluster_id: test-cluster
  client_id: consumer
  channel: session

http_server:
  ip: localhost
  port: 8080